# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titi',
            new_name='compony',
        ),
    ]
