# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0002_auto_20180105_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('adress', models.CharField(max_length=140)),
            ],
        ),
    ]
