# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compony',
            name='title',
        ),
        migrations.AddField(
            model_name='compony',
            name='amount',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
