# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0004_auto_20180105_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compony',
            name='amount',
        ),
        migrations.AddField(
            model_name='compony',
            name='adress',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
