# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0005_auto_20180105_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='compony',
            name='location',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
