# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0007_auto_20180105_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
