# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0009_auto_20180105_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compony',
            old_name='name',
            new_name='name_of_compony',
        ),
    ]
