# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0012_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='compony',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
