# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('try', '0013_auto_20180107_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='compony',
            field=models.ManyToManyField(null=True, to='try.compony'),
        ),
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
